plugins {
    id 'java'
    id 'application'

}

dependencies {
  implementation files("src/external/jna-jpms-5.16.0.jar")
}


java {
    sourceCompatibility = JavaVersion.VERSION_17  
}

sourceSets {
    main {
        java {
            srcDirs = ["src"]
        }
    }
}


jar {
  from {
    configurations.runtimeClasspath.filter {
      it.name.contains("jna")
    }.collect { zipTree(it) }
  }
    manifest {
        attributes(
          'Main-Class': 'Initer' 
      )
  }
}

tasks.named('run') {
    
  println "Running Initer class on default settings!"
  classpath = sourceSets.main.runtimeClasspath
  mainClass = "Initer"  
}

