plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17  
}

sourceSets {
    main {
        java {
            srcDirs = ["src"]
        }
    }
}

jar {
    manifest {
        attributes(
            'Main-Class': 'Initer'         )
    }
}



tasks.register('run', JavaExec) {
    
  println "Running Initer class on default settings!"
  classpath = sourceSets.main.runtimeClasspath
  mainClass = "Initer"  
}

