plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17  // Ajusta según tu versión de Java
}

sourceSets {
    main {
        java {
            srcDirs = ["src"]
        }
    }
}

tasks.register('run', JavaExec) {
    
  println "Running Initer class on default settings!"
  classpath = sourceSets.main.runtimeClasspath
  mainClass = "Initer"  
}

